<div class="container">
    <?php View::content() ?> 
    <h1>Formulario de contacto</h1>
    <?= Form::open() ?> 
        <label>Nombre:
            <?= Form::text('contacto.nombre', 'placeholder="Tu nombre *" required') ?> 
        </label>
        <label>Email :
            <?= Form::email('contacto.email', 'placeholder="Tu email *" required') ?> 
        </label>
        <?= Form::textarea('contacto.mensaje', 'rows=8 placeholder="Tu mensaje *" required') ?> 
        <div>
            <?= Form::submit('Enviar mensaje') ?> 
        </div>
    </form>
</div> 