<h2>Gracias a todos los colaboradores</h2>

  <?php
  ini_set("user_agent", 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/31.0.1650.63 Chrome/31.0.1650.63 Safari/537.36');
  $url = 'https://api.github.com/repos/KumbiaPHP/sandbox/contributors';
  $team = json_decode(file_get_contents($url));
  foreach ($team as $user) :?>
   <a href="https://github.com/<?= $user->login?>" data-tooltip="@<?= $user->login, ' ', $user->contributions, ' contribuciones'?>">
   <img src="<?= $user->avatar_url ?>&s=60" width=60 height=60 alt="@<?= $user->login?>"></a>
  <?php endforeach ?> 