<header>
    <div class="row container-top">
        <h1>Templates</h1>
        <p>Using KumbiaPHP templates</p>
    </div>
</header>
<div class="row">
    <h2></h2>
    <ul>
        <li><a href="/templates/get/csv" target="_blank">CSV Template</a></li>
        <li><a href="/templates/get/xml" target="_blank">XML Template</a></li>
        <li><a href="/templates/get/json" target="_blank">JSON Template</a></li>
    </ul>
</div>