<header class="container-top">
        <h1>Templates</h1>
        <p>Using KumbiaPHP templates</p>
</header>
<div class="container">
    <aside>
        <h2>KumbiaPHP Templates</h2>
        <pre class="language-php">
            <code class="language-php"><?= h('// Any method in the controller
public function users()
{
    $this->data = User::all(); // Send any data to $this->data
    View::select(null, "xml"); // Use any of xml, json or csv. That\'s all!
}'
) ?></code>
        </pre>
    </aside>
    <article>
        <h2>View this table in 
            <a href="/templates/get/json" role="button" target="_blank" data-tooltip="JSON Template">JSON</a>
            <a href="/templates/get/xml" role="button" target="_blank" data-tooltip="XML Template">XML</a>
            <a href="/templates/get/csv" role="button" target="_blank" data-tooltip="CSV Template">CSV</a>
        </h2>
        <?php if (!count($data)) : ?>
            <h2>There are no records</h2>
        <?php else : ?>
            <figure>
            <table class="report">
                <caption class="caption">User list</caption>
                <thead>
                    <tr>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Birthdate</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data as $item) : ?>
                        <tr>
                            <td><?= $item->first_name ?></td>
                            <td><?= $item->last_name ?></td>
                            <td><?= $item->email ?></td>
                            <td><?= $item->birthdate ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
            </figure>
        <?php endif ?>
    </article>
</div>
<?= Tag::js('prism') ?>
<?php Css::add('prism') ?> 