<header>
<div class="row container-top">    
    <div class="span10 page-header ">
        <h1>KumbiaPHP Framework Examples</h1>
        <h2>Programar puede ser más fácil.</h2>
        <p><small>Descarga KumbiaPHP y desarrolla aplicaciones web estables y rápidas.</small></p>
        <h3><a class="btn-large" href="https://github.com/KumbiaPHP/KumbiaPHP/archive/v1.0.0.zip">Descargar KumbiaPHP 1.0</a></h3>
		<!--<small><a href="#">Otras versiones</a> · <a href=#>Vagrant box</a></small>-->
    </div>   
</div>
</header>
<div class="row">
    <div class="span4">
        <h2>Reports</h2>
        <h3>mPDF</h3>
        <ul>
            <li><a href="/reports/mpdf">Export to PDF, includes header and footer</a></li>
        </ul>
    </div>
    <div class="span4">
        <h2>Partials</h2>
        <h3>Social</h3>
        <ul>
            <li><a href="/partials/social/sociable/">Sociable</a></li>
        </ul>
        <h3>Google</h3>
        <ul>
            <li>Google Maps</li>
        </ul>
    </div>
    <div class="span4">
        <h2>Colabora en GitHub añadiendo ejemplos</h2>
        <p>Sube tus ejemplos, para no repetirnos y ser más productivos.</p>
        <p><a href="https://github.com/KumbiaPHP/Sandbox" ><?= Html::img('sociable/github-img.jpeg', 'KumbiaPHP en github', 'width=120 height=46') ?>KumbiaPHP Sandbox en GitHub</a></p>
    </div>
</div>
<section class="row contributors">
    <?php View::partial('social/gitcontributors', '+1day')?> 
</section> 