<header>
<div class="row container-top">    
    <div class="span10 page-header ">
        <h1>KumbiaPHP Framework Sandbox Examples</h1>
        <h2>Programar puede ser más fácil.</h2>
        <p><small>Descarga KumbiaPHP y desarrolla aplicaciones web estables y rápidas.</small></p>
        <h3><a class="btn-large" href="https://github.com/KumbiaPHP/KumbiaPHP/archive/v1.0.0.zip">Descargar KumbiaPHP 1.0</a></h3>
		<!--<small><a href="#">Otras versiones</a> · <a href=#>Vagrant box</a></small>-->
    </div>   
</div>
</header>
<div class="row">
    <div class="span4">
        <h2>Rápido, ligero y flexible</h2>
        <p>KumbiaPHP es un framework para aplicaciones web libre escrito en <abbr title="Programación Orientada a Objetos">POO</abbr> PHP5. Basado en prácticas de desarrollo como <abbr title="Don't Repeat Yourself - No te repitas">DRY</abbr> y <abbr title="Keep It Short and Simple | Manténgalo breve y simple">KISS</abbr>, para software comercial y educativo.</P>
    <p>Fomenta la velocidad y eficiencia en la creación y mantenimiento de aplicaciones web. Reemplazando tareas de codificación repetitivas por poder, control y placer.</p>
    <p><?= Html::link('caracteristicas/', 'Quiero saber más.')?></p>	
        <?php //echo Html::img('rapido.png') ?> 
    </div>
    <div class="span4">
        <h2>Partials</h2>
        <h3>Social</h3>
        <ul>
            <li><a href="/partials/social/sociable/">Sociable</a></li>
        </ul>
        <h3>Google</h3>
        <ul>
            <li>Google Maps</li>
        </ul>
    </div>
    <div class="span4">
        <h2>Colabora en GitHub</h2>
        <p>Puedes descargar la última versión en desarrollo desde GITHub y disponer de las últimas correcciones, cambios y mejoras..</p>
        <p><a href="https://github.com/KumbiaPHP/KumbiaPHP" ><?= Html::img('sociable/github-img.jpeg', 'KumbiaPHP en github', 'width=120 height=46') ?>KumbiaPHP en GitHub</a></p>
    </div>
</div>
<section class="row contributors">
    <?php View::partial('social/gitcontributors', '+1day')?> 
</section>