<header class="container-top page-header">
    <h1>KumbiaPHP Framework Examples</h1>
    <h2>Programar puede ser más fácil.</h2>
    <p>Descarga KumbiaPHP y desarrolla aplicaciones web estables y rápidas.</p>
    <a class="btn-large" href="https://github.com/KumbiaPHP/KumbiaPHP/archive/refs/tags/v<?= KUMBIA_VERSION ?>.zip">Descargar KumbiaPHP <?= KUMBIA_VERSION ?></a>
</header>
<section class="container">
    <div class="grid">
        <article>
            <h2>Javascript</h2>
            <ul>
                <li><a href="/pages/kumbia/manual/js">KumbiaPHP Javascript</a></li>
            </ul>
            <h2>Templates</h2>
            <ul>
                <li><a href="/templates">KumbiaPHP Templates</a></li>
                <li><a href="/templates-examples/info/pdf">Export to PDF, includes header and footer</a></li>
            </ul>
        </article>
        <article>
            <h2>Partials</h2>
            <h3>Social</h3>
            <ul>
                <li><a href="/partials/social/sociable/">Sociable</a></li>
            </ul>
            <h3>Google</h3>
            <ul>
                <li>Google Maps</li>
            </ul>
        </article>
        <article class="action">
            <hgroup>
                <h2>Involúcrate</h2>
                <h3>Colabora en GitHub añadiendo ejemplos</h3>
            </hgroup>
            <div>
                <p>Sube tus ejemplos, para no repetirnos y ser más productivos.</p>
                <p>Crea un fork en Github:</p>
                <a href="https://github.com/KumbiaPHP/Sandbox" role="button">KumbiaPHP Sandbox en GitHub</a>
            </div>
        </article>
    </div>
</section>
    
<section class="container contributors">
    <?php View::partial('social/gitcontributors', '+1day') ?>
</section>