<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <title><?= $page_title ?></title>
    <!--[if lt IE 9]> <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/html5shiv@latest/dist/html5shiv.min.js"</script> <![endif]-->
	<link rel="stylesheet" href="/css/main.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="Sandbox with KumbiaPHP examples">
    <meta property="og:description" content="Offering examples to learn to use KumbiaPHP.">
    <meta property="og:url" content="https://sandbox.kumbiaphp.com/">
    <meta name="twitter:card" content="summary_large_image">
	<meta property="og:type" content="website">
    <meta property="og:image" content="https://sandbox.kumbiaphp.com/img/logo.png">
</head>
<body>
	<?php View::partial('main/topbar', null, array('menu' => $menu)) ?> 
	<main class="content">
            <?php View::content() ?> 
	</main>
<footer>
    <div class="container">
    <div class="row">
        <div class="six columns">
            <h3>Conecta con nosotros</h3>
            <p>Slack: <a href='https://slack.kumbiaphp.com' rel="me noopener noreferrer" target="_blank" title="Chat donde podrás encontrar ayuda a problemas que tengas, hacer comentarios, proponer ideas, reportar bugs, socializar temas relacionados y disfrutar de KumbiaPHP.">
            <img src="https://slack.kumbiaphp.com/badge.svg" alt="KumbiaPHP en Slack"></a></p>
            <p><a href="https://groups.google.com/group/kumbia/" rel="me" title="Grupo de Google de KumbiaPHP Framework">Grupo en Google</a> | 
            <a href="https://www.facebook.com/kumbia.fw" rel="me noopener noreferrer" target="_blank">Facebook</a> |
            <a href="https://twitter.com/KumbiaPHP" rel="me noopener noreferrer" target="_blank">Twitter</a></p>
        </div>
        <div class="three columns">
            <h3>Ejemplos</h3>
		    <?php View::partial('social/sociable') ?> 
        </div>
        <section class="three columns">
            <h3>KumbiaPHP</h3>
            <ul class="list">
                <li><a href="https://kumbiaphp.com/blog/" rel="me">Blog</a></li>
                <li><a href="https://github.com/KumbiaPHP/KumbiaPHP/" rel="me">Github</a></li>
                <li><a href="https://github.com/KumbiaPHP/Documentation/tree/master/es" rel="me">Manual</a></li>
            </ul> 
        </section>
    <p><?= 'KumbiaPHP v',KUMBIA_VERSION,' - Time: ', round((microtime(1) - $_SERVER['REQUEST_TIME_FLOAT']) * 1000, 4), ' ms.'; ?></p>
    </div></div>
</footer>
<!-- <script defer src="https://cdn.jsdelivr.net/npm/cookie-bar/cookiebar-latest.min.js"></script> -->
</body>
</html>
