<?php

use Mpdf\Mpdf;

/* Defaults */

// fileName
$fileName = $filename ?? "Reporte-de-$controller_name";

// Title
$title = $title ?? "Reporte de $controller_name";

// CSS
$css = $css ?? 'css/pdf.css';

// Destination
$destination = isset($download) && $download ? 'D' : 'I';

//Activa el almacenamiento en búfer de la salida
ob_start();

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <title><?= $title ?></title>
    <link rel="stylesheet" type="text/css" href="<?= $css ?>">
    <meta name="author" content="KumbiaPHP framework">
    <meta name="description" content="PDF output example with KumbiaPHP framework">
    <meta name="keywords" content="kumbiaphp, php, pdf, mpdf, examples">

<body>
    <htmlpageheader name="myHeader1">
        <section id="page-header">
            <a href="https://www.kumbiaphp.com"><img src="img/kumbiaphp.svg" alt="Logo KumbiaPHP"></a>
            <p>Powered by</p>
        </section>
    </htmlpageheader>

    <?php View::content() ?>

    <htmlpagefooter name="myFooter1">
        <section id="page-footer">
            <div id="printed-date">{DATE d/m/Y}</div>
            <div id="page-number">{PAGENO}/{nbpg}</div>
        </section>
    </htmlpagefooter>
</body>

</html>
<?php
$html = ob_get_clean();
ob_clean();

// Crea una instancia de la clase y le pasa el directorio temporal
$mpdf = new Mpdf([
    'tempDir' => APP_PATH . 'temp/mpdf',
    'format' => 'A4',
    'title2annots' => true,  // convert title in annotations
    'mirrorMargins' => 0,    // mirror the left and right margin values on odd and even pages 
    'exposeVersion' => false // security 
    // more variables in https://mpdf.github.io/reference/mpdf-variables/overview.html
]);

// Escribe el contenido HTML (Template + View):
$mpdf->WriteHTML($html);

// Genera el PDF, ya sea para su descarga o visualización en el navegador
$mpdf->Output("$fileName.pdf", $destination);
