<?php $page_title = 'Export PDF with mPDF - ' . $page_title; ?>
<header>
    <div class="row container-top">
        <h1>Export PDF with mPDF</h1>
        <p>Uses PDF template</p>
    </div>
</header>
<div class="row">
    <h2>Requirements</h2>
    <ul>
        <li><a href="https://mpdf.github.io/">mPDF</a> (Is a PHP library which generates PDF files from UTF-8 encoded HTML)</li>
    </ul>
    <h2>Test</h2>
    <ul>
        <li><a href="/reports/mpdf/pdf">Export list users</a></li>
    </ul>
    <h2>Links</h2>
    <ul>
        <li><a href="https://www.kumbiaphp.com/blog/2019/04/29/exportar-tabla-html-a-pdf/">Tutorial</a></li>
        <li><a href="https://github.com/kumbiaphp/sandbox/blob/master/app/views/_shared/templates/pdf.phtml">[PDF Template source]</a></li>
    </ul>
</div> 