<?php $page_title = 'Export PDF with mPDF - '.$page_title; ?>
<header>
    <div class="row container-top">
        <h1>Export PDF with mPDF</h1>
        <p>Uses template pdf</p>
    </div>
</header>
<div class="row">
    <ul>
        <li><a href="https://github.com/kumbiaphp/sandbox/blob/master/app/views/_shared/templates/pdf.phtml">PDF Template source</a></li>        
        <li><a href="/reports/mpdf/pdf">Export list users</a></li>
    </ul>
    
</div>
<div class="row">
    <code>
        
</div>