<?php if (!count($data)) : ?>
    <h2>No hay ningún registro</h2> 
<?php else : ?>
    <table class="report">
    <caption class="caption"><?= $title ?></caption>
        <thead>
            <tr>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Email</th>
                <th scope="col">Birthdate</th>
            </tr>
        </thead>
        <tbody> 
            <?php foreach ($data as $item) : ?>
                <tr>
                    <td><?= $item->first_name ?></td>
                    <td><?= $item->last_name ?></td>
                    <td><?= $item->email ?></td>
                    <td><?= $item->birthdate ?></td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
<?php endif ?> 