<header class="container-top">
    <h1>Export PDF with mPDF</h1>
    <p>Uses PDF template</p>
</header>
<section class="container">
<div class="row">
    <h2>Requirements</h2>
    <ul>
        <li><a href="https://mpdf.github.io/" target="_blank" rel="noopener noreferrer">mPDF</a> (Is a PHP library which generates PDF files from UTF-8 encoded HTML)</li>
    </ul>
    <h2>Test</h2>
    <ul>
        <li><a href="/templates_examples/pdf" target="_blank">Export list users</a></li>
    </ul>
    <h2>Sources</h2>
    <ul>
        <li><a href="https://github.com/kumbiaphp/sandbox/blob/master/app/views/_shared/templates/pdf/mpdf.phtml" target="_blank" rel="noopener noreferrer">PDF Template</a></li>
        <li><a href="https://github.com/kumbiaphp/sandbox/blob/master/app/controllers/templates_examples_controller.php#L11" target="_blank" rel="noopener noreferrer">Controller</a></li>
    </ul>
    <h2>Tutorials</h2>
    <ul>
        <li><a href="https://www.kumbiaphp.com/blog/2019/04/29/exportar-tabla-html-a-pdf/" target="_blank" rel="noopener noreferrer">Exportar tabla HTML a PDF</a></li>
        <li><a href="https://www.kumbiaphp.com/blog/2018/08/06/crear-pdf-usando-html/" target="_blank" rel="noopener noreferrer">Crear PDF usando HTML</a></li>
    </ul>
</div>
</section> 