<footer class="site-footer">
    <div class="row">
            <div class="span5">
                <p>Web creada con KumbiaPHP usando <?php echo Html::img('HTML5.png', 'HTML5'); ?></p>
            </div>
            <div class="span7" style="text-align: right">
                <h4>Comparte<h4> 
                <span class='st_facebook_large' displayText='Facebook'></span>
                <span class='st_twitter_large' displayText='Tweet'></span>
                <span class='st_googleplus_large' displayText='Google +'></span>
                <span class='st_linkedin_large' displayText='LinkedIn'></span>
                <span class='st_pinterest_large' displayText='Pinterest'></span>
                <span class='st_meneame_large' displayText='Meneame'></span>
                <span class='st_fresqui_large' displayText='Fresqui'></span>
                <span class='st_email_large' displayText='Email'></span>
                <span class='st_sharethis_large' displayText='ShareThis'></span>
            </div>
    </div>
</footer>
