<nav class="container">
    <ul><li>
        <a href="/" title="KumbiaPHP Framework ejemplos"><img src="/img/kumbiaphp.svg" alt="KumbiaPHP Framework" width="259" height="30"/></a>     
    </li></ul>
    <div>
    <label for="off-canvas">≡</label>
    <input type="checkbox" id="off-canvas">
    <ul class="menu <?= $menu ?>">
        <li><a href="/basic/" class="basic">Basic</a></li>
        <li><a href="/kumbia/" class="kumbia">Kumbia</a></li>
        <li><a href="/extras/" class="blog">Extras</a></li>
        <li><a href="/partials/" class="partials">Partials</a></li>
        <li><a href="/helpers/" class="helpers">Helpers</a></li>
        <li><a href="/about/" class="about">About</a></li>
    </ul>
</nav> 